"""
VentureMind AI — PDF Report Generator
Uses ReportLab to produce a professional, multi-section startup blueprint PDF.
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.platypus import (
    HRFlowable,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from app.core.logging import get_logger
from app.models.blueprint import Blueprint
from app.models.startup import StartupIdea

logger = get_logger(__name__)

# ── Colour palette ────────────────────────────────────────────────────────────
PRIMARY = colors.HexColor("#3b82d4")
SECONDARY = colors.HexColor("#7c5cd8")
DARK = colors.HexColor("#1f2328")
MUTED = colors.HexColor("#57606a")
LIGHT_BG = colors.HexColor("#f7f8fa")
WHITE = colors.white


def _styles() -> dict:
    base = getSampleStyleSheet()
    return {
        "title": ParagraphStyle(
            "Title",
            parent=base["Title"],
            fontSize=26,
            textColor=PRIMARY,
            alignment=TA_CENTER,
            spaceAfter=6,
        ),
        "subtitle": ParagraphStyle(
            "Subtitle",
            parent=base["Normal"],
            fontSize=13,
            textColor=MUTED,
            alignment=TA_CENTER,
            spaceAfter=20,
        ),
        "h1": ParagraphStyle(
            "H1",
            parent=base["Heading1"],
            fontSize=16,
            textColor=PRIMARY,
            spaceBefore=18,
            spaceAfter=6,
        ),
        "h2": ParagraphStyle(
            "H2",
            parent=base["Heading2"],
            fontSize=13,
            textColor=SECONDARY,
            spaceBefore=12,
            spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "Body",
            parent=base["Normal"],
            fontSize=10,
            textColor=DARK,
            leading=16,
            spaceAfter=4,
        ),
        "bullet": ParagraphStyle(
            "Bullet",
            parent=base["Normal"],
            fontSize=10,
            textColor=DARK,
            leading=16,
            bulletIndent=0,
            leftIndent=14,
            spaceAfter=3,
        ),
    }


def _hr(story: list) -> None:
    story.append(HRFlowable(width="100%", thickness=0.5, color=MUTED, spaceAfter=4))


def _h1(story: list, text: str, styles: dict) -> None:
    story.append(Paragraph(text, styles["h1"]))
    _hr(story)


def _h2(story: list, text: str, styles: dict) -> None:
    story.append(Paragraph(text, styles["h2"]))


def _body(story: list, text: str, styles: dict) -> None:
    if text:
        story.append(Paragraph(str(text), styles["body"]))


def _bullet_list(story: list, items: list, styles: dict) -> None:
    for item in items:
        if item:
            story.append(Paragraph(f"• {item}", styles["bullet"]))


def _kv_table(story: list, rows: list[tuple[str, str]], styles: dict) -> None:
    if not rows:
        return
    table_data = [[Paragraph(k, styles["body"]), Paragraph(str(v), styles["body"])] for k, v in rows]
    tbl = Table(table_data, colWidths=[5 * cm, 12 * cm])
    tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (0, -1), LIGHT_BG),
                ("TEXTCOLOR", (0, 0), (0, -1), MUTED),
                ("FONTSIZE", (0, 0), (-1, -1), 9),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#e5e7eb")),
                ("PADDING", (0, 0), (-1, -1), 6),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(tbl)
    story.append(Spacer(1, 8))


# ── Section builders ───────────────────────────────────────────────────────────

def _add_cover(story: list, startup: StartupIdea, styles: dict) -> None:
    story.append(Spacer(1, 2 * cm))
    story.append(Paragraph("VentureMind AI", styles["title"]))
    story.append(Paragraph("Autonomous Startup Blueprint", styles["subtitle"]))
    story.append(Spacer(1, 0.5 * cm))
    _hr(story)
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(f"<b>Startup Idea:</b> {startup.idea_text}", styles["body"]))
    if startup.industry:
        story.append(Paragraph(f"<b>Industry:</b> {startup.industry}", styles["body"]))
    if startup.country:
        story.append(Paragraph(f"<b>Country:</b> {startup.country}", styles["body"]))
    story.append(
        Paragraph(
            f"Generated by IBM Granite on {datetime.now().strftime('%B %d, %Y')}",
            styles["subtitle"],
        )
    )
    story.append(PageBreak())


def _add_executive_summary(story: list, data: dict | None, styles: dict) -> None:
    if not data:
        return
    _h1(story, "1. Executive Summary", styles)
    _body(story, data.get("problem", ""), styles)
    _body(story, data.get("solution", ""), styles)
    _body(story, data.get("market_opportunity", ""), styles)
    _body(story, data.get("business_model", ""), styles)


def _add_market_research(story: list, market: dict | None, competitors: list | None, swot: dict | None, personas: list | None, styles: dict) -> None:
    _h1(story, "2. Market Research & Intelligence", styles)
    if market:
        _h2(story, "Market Overview", styles)
        rows = [
            ("Market Size (TAM)", market.get("market_size", "—")),
            ("Growth Rate (CAGR)", market.get("growth_rate", "—")),
            ("Market Maturity", market.get("market_maturity", "—")),
        ]
        _kv_table(story, rows, styles)
        _h2(story, "Key Trends", styles)
        _bullet_list(story, market.get("key_trends", []), styles)

    if competitors:
        story.append(PageBreak())
        _h2(story, "Competitor Analysis", styles)
        for comp in competitors[:5]:
            _body(story, f"<b>{comp.get('name', '')}</b> — {comp.get('description', '')}", styles)
            _bullet_list(story, [f"Strength: {s}" for s in comp.get("strengths", [])[:2]], styles)
            _bullet_list(story, [f"Weakness: {w}" for w in comp.get("weaknesses", [])[:2]], styles)
            story.append(Spacer(1, 4))

    if swot:
        _h2(story, "SWOT Analysis", styles)
        swot_rows = [
            ("Strengths", ", ".join(swot.get("strengths", []))),
            ("Weaknesses", ", ".join(swot.get("weaknesses", []))),
            ("Opportunities", ", ".join(swot.get("opportunities", []))),
            ("Threats", ", ".join(swot.get("threats", []))),
        ]
        _kv_table(story, swot_rows, styles)

    if personas:
        _h2(story, "Customer Personas", styles)
        for p in personas[:3]:
            _body(story, f"<b>{p.get('name', 'Persona')}</b> ({p.get('age_range', '')}) — {p.get('occupation', '')}", styles)
            _bullet_list(story, [f"Pain: {x}" for x in p.get("pain_points", [])[:2]], styles)


def _add_business_model(story: list, bmc: dict | None, lean: dict | None, pricing: dict | None, styles: dict) -> None:
    story.append(PageBreak())
    _h1(story, "3. Business Model", styles)

    if bmc:
        _h2(story, "Business Model Canvas", styles)
        canvas_rows = [
            ("Value Propositions", ", ".join(bmc.get("value_propositions", []))),
            ("Customer Segments", ", ".join(bmc.get("customer_segments", []))),
            ("Revenue Streams", ", ".join(bmc.get("revenue_streams", []))),
            ("Key Activities", ", ".join(bmc.get("key_activities", []))),
            ("Key Resources", ", ".join(bmc.get("key_resources", []))),
            ("Key Partners", ", ".join(bmc.get("key_partners", []))),
            ("Channels", ", ".join(bmc.get("channels", []))),
        ]
        _kv_table(story, canvas_rows, styles)

    if pricing:
        _h2(story, "Pricing Strategy", styles)
        _body(story, f"Model: {pricing.get('model', '')} — {pricing.get('rationale', '')}", styles)
        for tier in pricing.get("tiers", [])[:3]:
            _body(story, f"<b>{tier.get('name', '')}</b>: {tier.get('price', '')}", styles)
            _bullet_list(story, tier.get("features", [])[:3], styles)


def _add_financial_plan(story: list, fin: dict | None, styles: dict) -> None:
    story.append(PageBreak())
    _h1(story, "4. Financial Plan", styles)
    if not fin:
        return
    projections = fin.get("projections", {})
    if projections:
        _h2(story, "3-Year Financial Projections", styles)
        rows = []
        for year, vals in projections.items():
            rows.append((year.replace("_", " ").title(), f"Revenue: {vals.get('revenue', '—')} | Expenses: {vals.get('expenses', '—')} | Profit: {vals.get('profit', '—')}"))
        _kv_table(story, rows, styles)

    break_even = fin.get("break_even", {})
    if break_even:
        _h2(story, "Break-Even Analysis", styles)
        be_rows = [
            ("Break-Even Point", break_even.get("break_even_point", "—")),
            ("Monthly Fixed Costs", break_even.get("monthly_fixed_costs", "—")),
            ("Price per Unit", break_even.get("price_per_unit", "—")),
        ]
        _kv_table(story, be_rows, styles)

    operational = fin.get("operational_costs", [])
    if operational:
        _h2(story, "Operational Cost Breakdown", styles)
        for cost in operational[:8]:
            _body(story, f"• {cost.get('category', '')}: {cost.get('monthly_estimate', '')}", styles)


def _add_funding_legal(story: list, funding: dict | None, legal: dict | None, styles: dict) -> None:
    story.append(PageBreak())
    _h1(story, "5. Funding & Legal Compliance", styles)
    if funding:
        schemes = funding.get("government_schemes", [])
        if schemes:
            _h2(story, "Government Schemes (Startup India / MSME)", styles)
            for s in schemes[:5]:
                _body(story, f"<b>{s.get('name', '')}</b>: {s.get('description', '')}", styles)
                _body(story, f"Benefit: {s.get('benefit', '')}", styles)
                story.append(Spacer(1, 3))

        stages = funding.get("stages", [])
        if stages:
            _h2(story, "Funding Roadmap", styles)
            for stage in stages:
                rows = [(stage.get("stage", ""), f"{stage.get('amount_range', '')} — {stage.get('timing', '')}")]
                _kv_table(story, rows, styles)

    if legal:
        _h2(story, "Legal & Compliance", styles)
        _body(story, f"Recommended Structure: {legal.get('recommended_structure', '')}", styles)
        regs = legal.get("registrations", [])
        if regs:
            _h2(story, "Required Registrations", styles)
            for r in regs:
                _body(story, f"<b>{r.get('name', '')}</b> ({r.get('timeline', '')}): {r.get('description', '')}", styles)
        checklist = legal.get("compliance_checklist", [])
        if checklist:
            _h2(story, "Compliance Checklist", styles)
            _bullet_list(story, checklist, styles)


def _add_strategy(story: list, marketing: dict | None, roadmap: list | None, risks: list | None, styles: dict) -> None:
    story.append(PageBreak())
    _h1(story, "6. Strategy & Roadmap", styles)

    if marketing:
        _h2(story, "Go-To-Market Strategy", styles)
        _bullet_list(story, marketing.get("distribution_channels", []), styles)
        _bullet_list(story, marketing.get("growth_hacks", []), styles)

    if roadmap:
        _h2(story, "Product Roadmap", styles)
        for item in roadmap[:6]:
            _body(story, f"<b>{item.get('quarter', '')}</b>: {item.get('milestone', '')}", styles)
            _bullet_list(story, item.get("features", [])[:3], styles)

    if risks:
        _h2(story, "Risk Matrix", styles)
        risk_rows = [
            (r.get("risk", ""), f"Impact: {r.get('impact', '')} | Mitigation: {r.get('mitigation', '')}")
            for r in risks[:6]
        ]
        _kv_table(story, risk_rows, styles)


def _add_investor_pitch(story: list, pitch: dict | None, styles: dict) -> None:
    if not pitch:
        return
    story.append(PageBreak())
    _h1(story, "7. Investor Pitch", styles)
    _body(story, f"<b>{pitch.get('headline', '')}</b>", styles)
    _body(story, pitch.get("elevator_pitch", ""), styles)
    rows = [
        ("Value Proposition", pitch.get("value_proposition", "—")),
        ("Why Now", pitch.get("why_now", "—")),
        ("Why Us", pitch.get("why_us", "—")),
        ("Financials Snapshot", pitch.get("financials_snapshot", "—")),
    ]
    _kv_table(story, rows, styles)
    if pitch.get("call_to_action"):
        _body(story, f"<b>Call to Action:</b> {pitch['call_to_action']}", styles)


def _add_recommendations(story: list, recs: dict | None, styles: dict) -> None:
    if not recs:
        return
    _h1(story, "8. Final Recommendations", styles)
    _bullet_list(story, recs.get("recommendations", []), styles)
    if recs.get("success_metrics"):
        _h2(story, "Success Metrics", styles)
        _bullet_list(story, recs["success_metrics"], styles)


# ── Public API ─────────────────────────────────────────────────────────────────

async def generate_pdf_report(startup: StartupIdea, blueprint: Blueprint) -> bytes:
    """
    Generate a full startup blueprint PDF and return raw bytes.

    Args:
        startup: StartupIdea ORM instance.
        blueprint: Blueprint ORM instance.

    Returns:
        PDF bytes ready to send as HTTP response or upload to COS.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        title="VentureMind AI — Startup Blueprint",
        author="VentureMind AI (IBM Granite)",
    )
    styles = _styles()
    story: list = []

    _add_cover(story, startup, styles)

    exec_sum = blueprint.executive_summary or {}
    _add_executive_summary(story, exec_sum, styles)

    fin = blueprint.financial_plan or {}
    _add_market_research(
        story,
        blueprint.market_research,
        blueprint.competitor_analysis,
        blueprint.swot_analysis,
        blueprint.customer_personas,
        styles,
    )
    _add_business_model(
        story,
        blueprint.business_model,
        blueprint.lean_canvas,
        fin.get("pricing"),
        styles,
    )
    _add_financial_plan(story, fin, styles)
    _add_funding_legal(
        story,
        blueprint.funding_opportunities,
        blueprint.legal_compliance,
        styles,
    )
    _add_strategy(
        story,
        blueprint.marketing_strategy,
        blueprint.product_roadmap,
        blueprint.risk_analysis,
        styles,
    )
    _add_investor_pitch(story, blueprint.investor_pitch, styles)
    _add_recommendations(story, blueprint.final_recommendations, styles)

    doc.build(story)
    logger.info("PDF generated", bytes=buf.tell())
    return buf.getvalue()
