// VentureMind AI — Export Page
import { useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  Download, FileText, RefreshCw, ChevronLeft,
  CheckCircle2, Loader2, ArrowRight,
} from 'lucide-react'
import { downloadPdf } from '@/services/api'

export default function ExportPage() {
  const { startupId } = useParams<{ startupId: string }>()
  const navigate = useNavigate()

  const [loading, setLoading] = useState(false)
  const [downloaded, setDownloaded] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleDownload = async () => {
    if (!startupId) return
    setLoading(true)
    setError(null)
    try {
      const blob = await downloadPdf(startupId)
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `venturemind_blueprint_${startupId.slice(0, 8)}.pdf`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      setDownloaded(true)
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'PDF generation failed. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  const sections = [
    'Executive Summary',
    'Market Research & Competitor Analysis',
    'SWOT Analysis & Customer Personas',
    'Business Model Canvas & Lean Canvas',
    'Financial Projections & Break-Even Analysis',
    'Funding Opportunities & Government Schemes',
    'Legal Compliance & Registration Checklist',
    'Go-To-Market Strategy & Product Roadmap',
    'Risk Analysis & Mitigation',
    'Investor Pitch Deck',
    'Final Recommendations',
  ]

  return (
    <div className="min-h-screen bg-surface py-10 px-6">
      <div className="max-w-2xl mx-auto">
        {/* Back */}
        <button
          onClick={() => navigate(`/blueprint/${startupId}`)}
          className="flex items-center gap-1.5 text-sm text-muted hover:text-dark transition-colors mb-8"
        >
          <ChevronLeft className="w-4 h-4" />
          Back to Blueprint
        </button>

        <motion.div
          initial={{ opacity: 0, y: 16 }}
          animate={{ opacity: 1, y: 0 }}
          className="card text-center"
        >
          {/* Icon */}
          <div className="w-16 h-16 rounded-2xl bg-primary/10 flex items-center justify-center mx-auto mb-5">
            <FileText className="w-8 h-8 text-primary" />
          </div>

          <h1 className="text-2xl font-bold text-dark mb-2">
            Download Your Startup Blueprint
          </h1>
          <p className="text-muted mb-8">
            A professionally formatted, investor-ready PDF report generated by IBM Granite.
          </p>

          {/* Contents List */}
          <div className="bg-surface rounded-xl border border-border p-5 mb-8 text-left">
            <h3 className="text-sm font-semibold text-dark mb-4">Report Contents</h3>
            <ul className="space-y-2">
              {sections.map((s, i) => (
                <li key={i} className="flex items-center gap-2.5 text-sm text-dark">
                  <CheckCircle2 className="w-4 h-4 text-green-500 flex-shrink-0" />
                  {s}
                </li>
              ))}
            </ul>
          </div>

          {/* Error */}
          {error && (
            <div className="text-sm text-red-600 bg-red-50 border border-red-200 rounded-xl px-4 py-3 mb-4">
              {error}
            </div>
          )}

          {/* Download Button */}
          {downloaded ? (
            <div className="flex flex-col items-center gap-4">
              <div className="flex items-center gap-2 text-green-600 text-sm font-medium">
                <CheckCircle2 className="w-5 h-5" />
                PDF downloaded successfully!
              </div>
              <div className="flex gap-3">
                <button onClick={handleDownload} className="btn-secondary flex items-center gap-2">
                  <Download className="w-4 h-4" /> Download Again
                </button>
                <button
                  onClick={() => navigate('/submit')}
                  className="btn-primary flex items-center gap-2"
                >
                  New Blueprint <ArrowRight className="w-4 h-4" />
                </button>
              </div>
            </div>
          ) : (
            <button
              onClick={handleDownload}
              disabled={loading}
              className="btn-primary w-full flex items-center justify-center gap-2 text-base py-4"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Generating PDF via IBM Cloud…
                </>
              ) : (
                <>
                  <Download className="w-5 h-5" />
                  Download PDF Report
                </>
              )}
            </button>
          )}
        </motion.div>

        {/* Actions */}
        <div className="flex gap-3 mt-6">
          <button
            onClick={() => navigate('/submit')}
            className="flex-1 btn-secondary flex items-center justify-center gap-2"
          >
            <RefreshCw className="w-4 h-4" /> Start New Blueprint
          </button>
          <button
            onClick={() => navigate(`/blueprint/${startupId}`)}
            className="flex-1 btn-secondary flex items-center justify-center gap-2"
          >
            <FileText className="w-4 h-4" /> View Blueprint
          </button>
        </div>
      </div>
    </div>
  )
}
